/**
 * 389 Find the Difference
 *
 * Easy
 *
 * You are given two strings s and t.
 *
 * String t is generated by random shuffling string s and then add one more letter at a random position.
 *
 * Return the letter that was added to t.
 *
 *
 *
 * Example 1:
 *
 * Input: s = "abcd", t = "abcde"
 * Output: "e"
 * Explanation: 'e' is the letter that was added.
 * Example 2:
 *
 * Input: s = "", t = "y"
 * Output: "y"
 *
 *
 * Constraints:
 *
 * 0 <= s.length <= 1000
 * t.length == s.length + 1
 * s and t consist of lowercase English letters.
 */
fun main() {
    val s = "abcd"
    val t = "abcde"
    findTheDifference(s, t)
}

/**
 * Преобразовываем большую строку t в мапу с подсчетом совпадений символов
 * Проходимся по второму слову s и уменьшаем значение в мапе для каждого совпадения символа
 * Возвращает оставшийся один символ с количеством 1
 */
fun findTheDifference(s: String, t: String): Char {
    val map = mutableMapOf<Char, Int>()

    // Преобразовываем большую строку t в мапу с подсчетом совпадений символов
    t.forEach {
        map.merge(it, 1, Int::plus)
    }

    // Проходимся по второму слову s и уменьшаем значение в мапе для каждого совпадения символа
    s.forEach {
        map.merge(it, 1, Int::minus)
    }

    // Возвращает оставшийся один символ с количеством 1
    return map.entries.first { entry -> entry.value == 1 }.key
}